export const videoStats = {
    "/public/African/African_Folktales,_Reimagined_-_short_films_by_Netflix___UNESCO_-_trailer(720p).mp4": { size: "17.3 MB", quality: "720p" },
    "/public/African/Ayanda_Official_Trailer_1__2015__-_Jafta_Mamabolo,_Fulu_Moguvhani_Movie_HD(720p).mp4": { size: "25.6 MB", quality: "720p" },
    "/public/African/Blood_Sisters___Official_Trailer___Netflix(720p).mp4": { size: "12.9 MB", quality: "720p" },
    "/public/African/Blood___Water_Season_2___Official_Trailer___Netflix(720p).mp4": { size: "13.0 MB", quality: "720p" },
    "/public/African/INKABI_THE_HITMAN_2024_l_OFFICIAL_TRAILER_4K(720p).mp4": { size: "13.4 MB", quality: "720p" },
    "/public/African/MERRYMEN_2__ANOTHER_MISSION__OFFICIAL_TRAILER(720p).mp4": { size: "35.8 MB", quality: "720p" },
    "/public/African/THE_WOMAN_KING_?_Official_Trailer__HD_(720p).mp4": { size: "10.9 MB", quality: "720p" },
    "/public/African/WAKA_WAKA___OFFICIAL_TRAILER(720p).mp4": { size: "5.6 MB", quality: "720p" },
    "/public/African/Where_Hands_Touch___Official_Trailer__HD____Vertical_Entertainment(720p).mp4": { size: "7.3 MB", quality: "720p" },
    "/public/my list/Blacklist.mp4": { size: "10.4 MB", quality: "HD" },
    "/public/trailer/resurrection.mp4": { size: "22.7 MB", quality: "HD" },
    "/public/my list/The loser.mp4": { size: "38.7 MB", quality: "HD" },
    "/public/Negeria/Army_of_the_Dead___Official_Trailer___Netflix(720p).mp4": { size: "14.3 MB", quality: "720p" },
    "/public/Negeria/Babel_-_Trailer(720p).mp4": { size: "39.2 MB", quality: "720p" },
    "/public/Negeria/Before_30_Official_Trailer(720p).mp4": { size: "14.2 MB", quality: "720p" },
    "/public/Negeria/El_hoyo_-_Trailer__HD_(720p).mp4": { size: "10.6 MB", quality: "720p" },
    "/public/Negeria/FBOY_Island___Trailer___HBO_Max(1080p).mp4": { size: "23.2 MB", quality: "1080p" },
    "/public/Negeria/John_Wick_Trailer_1.mp4": { size: "8.2 MB", quality: "HD" },
    "/public/Negeria/KATE___Official_Trailer___Netflix(720p).mp4": { size: "9.9 MB", quality: "720p" },
    "/public/Negeria/Marvel_s_Daredevil___Official_Trailer_[HD]___Netflix(720p).mp4": { size: "12.8 MB", quality: "720p" },
    "/public/Negeria/Mosul_Trailer_1.mp4": { size: "21.5 MB", quality: "HD" },
    "/public/Negeria/Peaky_Blinders_-_Season_1___Trailer(720p).mp4": { size: "6.9 MB", quality: "720p" },
    "/public/new release/Citation___Official_Trailer___Netflix(720p).mp4": { size: "17.1 MB", quality: "720p" },
    "/public/new release/FAST_X___Official_Trailer(720p).mp4": { size: "21.0 MB", quality: "720p" },
    "/public/new release/LOCKED_UP___Official_Trailer___The_Asylum(720p).mp4": { size: "9.9 MB", quality: "720p" },
    "/public/new release/Rez_Ball___Official_Trailer___Netflix(720p).mp4": { size: "7.8 MB", quality: "720p" },
    "/public/new release/Sugar_Rush___The_Official_Trailer(720p).mp4": { size: "20.0 MB", quality: "720p" },
    "/public/new release/THE_EQUALIZER_3_-_Official_Red_Band_Trailer__HD_(720p).mp4": { size: "10.4 MB", quality: "720p" },
    "/public/new release/The_Fast_and_the_Furious_2001_Trailer.mp4": { size: "21.5 MB", quality: "HD" },
    "/public/new release/Troll_2___Official_Trailer___Netflix(720p).mp4": { size: "11.9 MB", quality: "720p" },
    "/public/new release/VENOM_-_Official_Trailer__HD_(720p).mp4": { size: "11.7 MB", quality: "720p" },
    "/public/originals/Bel-Air___Official_Trailer(720p).mp4": { size: "14.7 MB", quality: "720p" },
    "/public/originals/Enola_Holmes___Official_Trailer___Netflix(720p).mp4": { size: "10.6 MB", quality: "720p" },
    "/public/originals/Extraction___Official_Trailer___Screenplay_by_JOE_RUSSO_Directed_by_SAM_HARGRAVE___Netflix(720p).mp4": { size: "12.7 MB", quality: "720p" },
    "/public/originals/Glass_Onion__A_Knives_Out_Mystery___Official_Trailer___Netflix(720p).mp4": { size: "10.5 MB", quality: "720p" },
    "/public/originals/Kasanova_Official_Trailer___Prime_Video___Starring_Wale_Ojo,_Ireti_Doyle,_Toyin_Abraham(720p).mp4": { size: "22.4 MB", quality: "720p" },
    "/public/originals/Maestro___Official_Trailer___Netflix(720p).mp4": { size: "10.1 MB", quality: "720p" },
    "/public/originals/Money_Heist___Series_Trailer___Netflix(720p).mp4": { size: "10.7 MB", quality: "720p" },
    "/public/originals/Rebel_Ridge___Official_Trailer___Netflix(720p).mp4": { size: "7.4 MB", quality: "720p" },
    "/public/originals/The_School_for_Good_and_Evil___Official_Trailer___Netflix(720p).mp4": { size: "12.5 MB", quality: "720p" },
    "/public/originals/True_Memoirs_of_an_International_Assassin___Official_Trailer_[HD]___Netflix(720p).mp4": { size: "28.9 MB", quality: "720p" },
    "/public/Popular/Barbarians___Official_Trailer___Netflix(720p).mp4": { size: "8.3 MB", quality: "720p" },
    "/public/Popular/Before_30_Official_Trailer(720p).mp4": { size: "14.2 MB", quality: "720p" },
    "/public/Popular/Game_of_Thrones___Official_Series_Trailer__HBO_(720p).mp4": { size: "16.5 MB", quality: "720p" },
    "/public/Popular/Hubie_Halloween_starring_Adam_Sandler___Official_Trailer___Netflix(720p).mp4": { size: "13.8 MB", quality: "720p" },
    "/public/Popular/LOEV___Official_Trailer_[HD]__2017____Shiv_Pandit,_Dhruv_Ganesh,_Siddharth_Menon(720p).mp4": { size: "15.6 MB", quality: "720p" },
    "/public/Popular/Love_Like_the_Falling_Petals___Official_Trailer___Netflix(720p).mp4": { size: "17.6 MB", quality: "720p" },
    "/public/Popular/Official_Trailer___Season_1___LUCIFER(720p).mp4": { size: "30.1 MB", quality: "720p" },
    "/public/Popular/The_Adam_Project___Official_Trailer___Netflix(720p).mp4": { size: "13.1 MB", quality: "720p" },
    "/public/Popular/Things_Heard___Seen_starring_Amanda_Seyfried___Official_Trailer___Netflix(720p).mp4": { size: "10.1 MB", quality: "720p" },
    "/public/Popular/What_Happened_to_Monday___Official_Trailer_[HD]___Netflix(720p).mp4": { size: "9.7 MB", quality: "720p" },
    "/public/Trending/Better_Call_Saul___Series_Trailer_[HD]___Netflix(720p).mp4": { size: "9.3 MB", quality: "720p" },
    "/public/Trending/YOU___Series_Trailer___Netflix(1080p).mp4": { size: "12.1 MB", quality: "1080p" },
    "/public/watch/Bad_Boys__1995__Official_Trailer_1_-_Will_Smith_Movie(720p).mp4": { size: "18.4 MB", quality: "720p" },
    "/public/watch/Better_Call_Saul___Series_Trailer_[HD]___Netflix(720p).mp4": { size: "9.3 MB", quality: "720p" },
    "/public/watch/The_Old_Guard___Official_Trailer___Netflix(720p).mp4": { size: "9.8 MB", quality: "720p" }
};
